osx_image: xcode9.4
language: objective-c
script:
  - xcodebuild -configuration Release -scheme B2Kit\ \(macOS\ Framework\) clean build test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" ENABLE_TESTABILITY=YES
  - xcodebuild -configuration Release -scheme B2Kit\ \(iOS\ Framework\) -destination "OS=11.4,name=iPhone X" clean build test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" ENABLE_TESTABILITY=YES
  - xcodebuild -configuration Release -scheme B2Kit\ \(tvOS\ Framework\) -destination "OS=11.4,name=Apple TV 4K" clean build test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" ENABLE_TESTABILITY=YES
  - xcodebuild -configuration Release -scheme B2Kit\ \(watchOS\ Framework\) clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" ENABLE_TESTABILITY=YES
