osx_image: xcode9
language: objective-c
script:
  - xcodebuild -configuration Release -scheme B2Kit\ \(macOS\ Framework\) clean build
  - xcodebuild -configuration Release -scheme B2Kit\ \(iOS\ Framework\) clean build
  - xcodebuild -configuration Release -scheme B2Kit\ \(tvOS\ Framework\) clean build
  - xcodebuild -configuration Release -scheme B2Kit\ \(watchOS\ Framework\) clean build
